### ISSUE TITLE
PackageNotFound

### ISSUE THREAD

**Issue by nimasteryang** [duyali2000/SemanticFlowGraph#2]
In both environment-gpu.yml and environment-cpu.yml, there is a package of pytorch==0.9.0, however, this version is not supported by PyTorch currently and not able to download from conda. When I try to create the conda env from the yaml file, it give error of:

`Solving environment: failed

ResolvePackageNotFound: 
  - pytorch==0.9.0=py3.7_cuda11.4.243_cudnn7.6.3_0`

Can you please update the yml file and align with the version that have pytorch official support https://pytorch.org/get-started/previous-versions ?

**Comment by duyali2000** [comment]
You can choose the torch version that suits your environment and cuda. Here's a possible solution to your problem.
For Linux and Windows:
# CUDA 11.6
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.6 -c pytorch -c nvidia
# CUDA 11.7
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia
# CPU Only
conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 cpuonly -c pytorch
