### ISSUE TITLE
hard-coded local pretrained model path

### ISSUE THREAD

**Issue by agb94** [duyali2000/SemanticFlowGraph#3]
https://github.com/duyali2000/SemanticFlowGraph/blob/0f52a0bba75473507a82b45371914a6104b25c59/model/tokenizer.py#L224

I encountered an error while trying to run the replication package. Can you please take a look into this matter? Thank you. :-)

**Comment by duyali2000** [comment]
This is a typo error and I have updated the file tokenizer.py. Thank you for your concern very much!
