### ISSUE TITLE
Hope a more detailed data description

### ISSUE THREAD

**Issue by fcmgdata** [duyali2000/SemanticFlowGraph#4]
I encountered a problem while understanding the /data/ folder. The number of commits in the /data/project/commits folder is inconsistent with the number mentioned in the paper. And I don't understand the meanings of .tsv and .txt files in the /data/project/ folder, respectively. Can you explain in more detail? Thank you!

**Comment by duyali2000** [comment]
The files with the suffix .tsv are the mapping files in different granularity (commits-, files-, hunks-), where each line is a mapping from the index of the commit file to the commit sha. The open_ts.txt and fix_ts.txt are the timestamps of the commits, which are used to sort fixing times and get the newest timestamp to ensure all bugs are closed by this time, meaning that all introducing commits must have appeared.
